services:
  db:
    image: postgres:18.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: solaceassignment
    volumes:
      - psql:/var/lib/postgresql/
    ports:
      - 5432:5432
volumes:
  psql:
